//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeScanner.DSA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public int Id { get; set; }
        public System.DateTime AbsenceDate { get; set; }
        public string Document { get; set; }
        public string Remark { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
