//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeScanner.DSA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Activity { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    }
}
