//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeScanner.Wab.CardReaderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardReaderService.ICardReaderService")]
    public interface ICardReaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardReaderService/DoWork", ReplyAction="http://tempuri.org/ICardReaderService/DoWorkResponse")]
        TimeScanner.DSA.EF.Employee DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICardReaderService/DoWork", ReplyAction="http://tempuri.org/ICardReaderService/DoWorkResponse")]
        System.Threading.Tasks.Task<TimeScanner.DSA.EF.Employee> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardReaderServiceChannel : TimeScanner.Wab.CardReaderService.ICardReaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardReaderServiceClient : System.ServiceModel.ClientBase<TimeScanner.Wab.CardReaderService.ICardReaderService>, TimeScanner.Wab.CardReaderService.ICardReaderService {
        
        public CardReaderServiceClient() {
        }
        
        public CardReaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardReaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardReaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardReaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TimeScanner.DSA.EF.Employee DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<TimeScanner.DSA.EF.Employee> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
